version: '3'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "10080:10080"
    environment:
      - NODE_ENV=development
      - DB_MAX_CONNECTION=10
      - DB_MIN_CONNECTION=0
      - DB_TIMEZONE=Asia/Seoul
      - DB_TYPE=mariadb
      - DB_HOST=healthmanager-1.cvbiskcgjdml.ap-northeast-2.rds.amazonaws.com
      - DB_USERNAME=hm_admin
      - DB_PASSWORD=Elql1015%^
      - DB_PORT=13306
      - DB_DATABASE=health_manager